server:
  port: 8080
spring:
  application:
    name: account
  profiles:
    active:
      - 'prod'
  config:
    import: 'optional:configserver:http://localhost:8083/'
#  rabbitmq:
#    host: 'localhost'
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:database/master.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
