server:
  port: 8080
spring:
  application:
    name: account
  profiles:
    active:
      - 'prod'
  config:
    import: 'optional:configserver:http://localhost:8083/'
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
#  rabbitmq:
#    host: 'localhost'
#    port: 5672
#    username: guest
#    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/account_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    change-log: classpath:database/master.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: 'http://localhost:8070/eureka/'

info:
  app:
    name: "account"
    description: "Account application"
    version: 1.0.0

logging:
  level:
    com:
      microservices:
        account: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration:
        seconds: 0.1
      exponential-backoff-multiplier: 2
      enable-exponential-backoff: true
      ignore-exceptions:
        - java.lang.NullPointerException
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j:
  ratelimiter:
    configs:
      default:
        timeout-duration: 1s
        limit-refresh-period: 5s
        limit-for-period: 1
