spring:
  application:
    name: gateway
  config:
    import: 'optional:configserver:http://localhost:8083/'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gateway"
    description: "Gateway application"
    version: 1.0.0

logging:
  level:
    com:
      microservices:
        gateway: DEBUG