build:
  version: '1.0'

account:
  message: 'Welcome to account related prod API'
  contactDetails:
    name: 'prod'
    email: 'prod@test.com'
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384