build:
  version: '3.0'

card:
  message: 'Welcome to card related local API'
  contactDetails:
    name: 'local'
    email: 'local@test.com'
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384