build:
  version: '3.0'

loan:
  message: 'Welcome to loan related local API'
  contactDetails:
    name: 'local'
    email: 'local@test.com'
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384