services:
  rabbitmq:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    container_name: rabbit-mq
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: 'thienan8928/configserver:v1'
    build:
      context: ../../configserver
      dockerfile: ../configserver/Dockerfile
    container_name: config-server
    ports:
      - '8083:8083'
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: 'curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1'
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservices-base-config

  account:
    image: 'thienan8928/account:v1'
    build:
      context: ../../account
      dockerfile: ../account/Dockerfile
    container_name: account
    ports:
      - '8080:8080'
    environment:
      SPRING_APPLICATION_NAME: 'account'
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  card:
    image: 'thienan8928/card:v1'
    build:
      context: ../../card
      dockerfile: ../card/Dockerfile
    container_name: card
    ports:
      - '8081:8081'
    environment:
      SPRING_APPLICATION_NAME: 'card'
    extends:
      file: common-config.yml
      service: microservices-configserver-config

  loan:
    image: 'thienan8928/loan:v1'
    build:
      context: ../../loan
      dockerfile: ../loan/Dockerfile
    container_name: loan
    ports:
      - '8082:8082'
    environment:
      SPRING_APPLICATION_NAME: 'loan'
    extends:
      file: common-config.yml
      service: microservices-configserver-config

networks:
  my-network:
    driver: bridge