services:
  network-deploy-service:
    networks:
      - my-network

  microservices-database-config:
    extends:
      service: network-deploy-service
    image: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  microservices-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 512m
    environment:
#      SPRING_RABBITMQ_HOST: 'rabbitmq'
      GITHUB_REPO_NAME: 'your-repo'
      GITHUB_USERNAME: 'your-username'
      GITHUB_PASSWORD: 'your-password'

  microservices-configserver-config:
    extends:
      service: microservices-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: 'configserver:http://configserver:8083/'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  microservices-eurekaserver-config:
    extends:
      service: microservices-configserver-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eurekaserver:8070/eureka/'
