server:
  port: 8083
spring:
  application:
    name: configserver
  profiles:
    active: git
#    active: native
#  rabbitmq:
#    host: 'localhost'
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_REPO_NAME:your-repo-config}
          username: ${GITHUB_USERNAME:your-username}
          password: ${GITHUB_PASSWORD:your-password}
          default-label: main
          timeout: 15
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: 'classpath:/config'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
